### ISSUE TITLE
Problems installing the plugin

### ISSUE THREAD

**Issue by mcazulo** [francesconero/elasticsearch-concatenate-token-filter#1]
Hi,

I was interested in trying out your plugin.

I am trying it with a test index.

``` javascript
{
    "settings": {
        "number_of_shards":2,
        "number_of_replicas":2,
        "_source":{
            "compress":true
        },
         "_default_" : {},
        "analysis": {
            "filter": {
                "concatenate":{
                    "type":"concatenate",
                    "token_separator":"_"
                }
            }
        }
    }
}
```

But I keep getting this error:

``` javascript
{
   "error": "IndexCreationException[[wss_test] failed to create index]; nested: ElasticsearchIllegalArgumentException[failed to find token filter type [concatenate] for [concatenate]]; nested: NoClassSettingsException[Failed to load class setting [type] with value [concatenate]]; nested: ClassNotFoundException[org.elasticsearch.index.analysis.concatenate.ConcatenateTokenFilterFactory]; ",
   "status": 400
}
```

Any ideas?

**Comment by francesconero** [comment]
Hi! Have you restarted the elasticsearch instance after installing the plugin?

**Comment by mcazulo** [comment]
Hi thanks for the reply, and yes I did restart it.
What I then tried was your version 1.0 instead and that worked perfectly.

**Comment by francesconero** [comment]
What version of Elastic are you using?

I can't seem to replicate the problem, so debugging it is difficult for me. Whatever additional information you have would be great!

Watch out with 1.0, as array fields get concatenated as well.

**Comment by francesconero** [comment]
It would be great if you could post your elasticsearch log after a restart (with the 1.1 plugin installed).

It should show that the plugin loaded properly like:

```
[2015-09-18 17:10:42,913][INFO ][plugins                  ] [Druid] loaded [ConcatenatePlugin], sites []
```

**Comment by mcazulo** [comment]
Hey turns out when I try and adding the plugin filter (master version) to my index settings I get a java error on the concatenateTokenFilterFactory.java `return new ConcatenateFilter(Version.LATEST, tokenStream, tokenSeparator, incrementGap);`  it cannot find the field LATEST in version.LATEST. I am using lucene version 4.6 which doesn't seem to have that field in utils.version. Any recommendations? Upgrading our elasticsearch at the moment is not an option and we have it at version 1.03. Thank you.
