### ISSUE TITLE
No licence

### ISSUE THREAD

**Issue by mattwelke** [francesconero/elasticsearch-concatenate-token-filter#14]
I notice that this repo currently has no open source licence. When I follow the discussion back to the original Elasticsearch forum post from ~2014 it's clear that the author of the code (and then, the author of this plugin, who used that code) intended it to be open source.

Can the author of this plugin choose a licence for the repo to help with organizations using the code in their own projects?

**Comment by mattwelke** [comment]
@francesconero Tagging you for visibility

**Comment by francesconero** [comment]
Of course, sorry I've been really busy lately and haven't been checking on this repository much.

Do you think a standard MIT license would do or is it too permissive?

@bomberby are you ok with it? You have contributed to this repo as well.

**Comment by mattwelke** [comment]
My organization would like to use the code and we'd be happy with either MIT or Apache. We appreciate the work you've put into it and assuming our work with porting it to 6.3 goes smoothly, we can push that work back upstream (though at this time, we don't have the resources to commit to maintaining it).

**Comment by francesconero** [comment]
I actually contacted the user who originally posted the code, and am now waiting either for him to answer me via email or join the discussion here. I think that the best thing is for him to decide under which license his code is released under, do you agree?

**Comment by bomberby** [comment]
MIT sounds great to me!
Lets see what the original author think.

**Comment by francesconero** [comment]
So @stephanebastian said that we can do whatever we want with the code, so I'll add a MIT license!

Thanks Stéphane!

**Comment by mattwelke** [comment]
Sounds great. :)

**Comment by francesconero** [comment]
Done, thank you @welkie for bringing up the issue.

Please open a pull request if you add support for ES 6.3!

**Comment by francesconero** [comment]
Ok sorry, apparently I didn't remember but I had already declared an Apache license in the POM file, so I'm switching to that one. They are very similar in any case.
