### ISSUE TITLE
Unable to install plugin on ES 2+

### ISSUE THREAD

**Issue by bomberby** [francesconero/elasticsearch-concatenate-token-filter#2]
Hi, due to the changes made to ES on 2+ this plugin can no longer be installed.
I've created a fork at https://github.com/bomberby/elasticsearch-concatenate-token-filter/tree/es-2.2 that allows me to install on 2.2.0, and https://github.com/bomberby/elasticsearch-concatenate-token-filter/tree/es-2.2.1 for 2.2.1(versions I personally needed).
I think you probably need to switch to versioning of the plugin to support newer ES, Is there anything i can do to help?

**Comment by francesconero** [comment]
Would your fork be backward compatible? I'm really not an expert on the elasticsearch plugin environment, but if that would be the case I would be very glad to accept a pull request!

**Comment by bomberby** [comment]
Unfortunately, it is not, ElasticSearch changed variables names and the way plugins install.
One option i can think of is to create a version meant for 1.X(the current one), and another for higher versions, but i'm not sure if we can have one that will fit all 2.X, or will need to generate one for each version.

**Comment by francesconero** [comment]
Oh that's unfortunate. What do you think would be the best thing? Keeping two separate repositories? Would you maintain the 2.X version?

**Comment by bomberby** [comment]
I think having under this repository multiple versions on branches would probably be the best, and people coming to use this plugin will be able to see it straight away. Installation could be performed via
`sudo bin/plugin install francesconero/elasticsearch-concatenate-token-filter/2.2.0` for example

**Comment by francesconero** [comment]
So just have a 1.X and a 2.X branch?

**Comment by bomberby** [comment]
This will be the fastest solution, your 1.X is known to work, and the 2.X could probably use more testing, but it's working for me on 2.2, this will enable users to enjoy both worlds.

**Comment by francesconero** [comment]
Great, so I should open a 2.X branch so that you can use it as a target for your pull request, correct?

**Comment by bomberby** [comment]
Yes, Please open 2.2.0 Branch, as i'm not sure if my fork works on 2.0 and 2.1

**Comment by francesconero** [comment]
I've created the 2.2.0 branch and waiting for your pull request

**Comment by bomberby** [comment]
Thank you, created at #3

**Comment by francesconero** [comment]
Closing after accepting #3

**Comment by francesconero** [comment]
@bomberby would you like to be added as a collaborator to the repo?

**Comment by bomberby** [comment]
Sure, if you want to, but don't count on my Java skills.

**Comment by francesconero** [comment]
Done, at least you seem to be more up to date with current releases of ES (I've stopped using it temporarily). Thanks for the PR!
