### ISSUE TITLE
does not work with latest elasticsearch v2.3.3

### ISSUE THREAD

**Issue by maheshgawali** [francesconero/elasticsearch-concatenate-token-filter#6]
`ERROR: Plugin [concatenate] is incompatible with Elasticsearch [2.3.3]. Was designed for version [2.2.2]`

good job though you guys, this is very much needed in ES

**Comment by bomberby** [comment]
Hi,
Can you please try vs the newly created 2.3.3 branch and tell me if this installs correctly?
(sudo bin/plugin install francesconero/elasticsearch-concatenate-token-filter/2.3.3)

**Comment by francesconero** [comment]
Great job keeping this plugin up to date @bomberby.

I would like to start thinking about automating new version releases, at least when it's just a matter of bumping versions in configuration files. I'll open an issue about it as soon as I have some time.

**Comment by bomberby** [comment]
It's bumping version and compiling with maven the new files, pretty simple, doesn't take a lot of time once i remember how to do it.

**Comment by maheshgawali** [comment]
@bomberby 👍 installed with Elasticsearch v2.3.3 and works now, thanks a lot :)
