### ISSUE TITLE
Cannot start elasticsearch after installing the plugin

### ISSUE THREAD

**Issue by janakaonline** [francesconero/elasticsearch-concatenate-token-filter#8]
Hi, I installed the plugin and when I try to start the server I am getting

[2016-08-01 10:19:36,719][WARN ][indices.cluster          ] [Ringer] [[.kibana][0]] marking and sending shard failed due to [failed to create index]
[.kibana] IndexCreationException[failed to create index]; nested: IllegalStateException[[index.version.created] is not present in the index settings for index with uuid: [null]];

(I have attached the screenshot of the error as well)

I'm using elastic search 2.2.0, Any idea how to solve this? 

are there any pre requirements?

Thanks
![capture](https://cloud.githubusercontent.com/assets/1264767/17284270/eaf6637c-57d6-11e6-84e7-cb358917c758.PNG)

**Comment by bomberby** [comment]
Pretty sure this is a clone of #4.

Solution i suggested there that worked was the following:

My solution was to add to the elasticsearch.yml file the following line:
index.version.created: 2020099

Much thanks to this helpful answer http://stackoverflow.com/questions/27685698/elasticsearchillegalstateexceptionindex-version-created-is-not-present-in-the

**Comment by janakaonline** [comment]
Aha.. it worked... thanks a lot
:)

**Comment by bomberby** [comment]
Glad to help!
